name: dart_swagger_to_models
description: >
  CLI-инструмент для генерации Dart-моделей из Swagger/OpenAPI спецификаций
  (JSON/YAML) с поддержкой null-safety.
version: 0.1.0

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.6.0
  crypto: ^3.0.5
  http: ^1.2.2
  yaml: ^3.1.3
  path: ^1.9.0

dev_dependencies:
  build: ^2.4.0
  build_runner: ^2.4.0
  lints: ^6.0.0
  test: ^1.25.6
