name: dart_example
description: Example Dart project using dart_swagger_to_models with build_runner
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  dart_swagger_to_models:
    path: ../../
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.8.0
